### ISSUE TITLE
rawdata may be missing from return

### ISSUE THREAD

**Issue by yespire** [kevinoo/phpWhois#9]
@kevinoo 

Just noticed an exception triggered by whois "IP", here are a few IPs that triggered the following exception
- 38.170.39.124
- 38.131.5.82

```
Exception-Code: 2
Exception-Message: Undefined array key "rawdata"
File: vendor/kevinoo/phpwhois/src/Handlers/RwhoisHandler.php
Line: 42
Trace: `#0 vendor/kevinoo/phpwhois/src/Handlers/RwhoisHandler.php(42): Whoops\Run->handleError()
#1 vendor/kevinoo/phpwhois/src/WhoisClient.php(495): phpWhois\Handlers\RwhoisHandler->parse()
#2 vendor/kevinoo/phpwhois/src/Handlers/IpHandler.php(167): phpWhois\WhoisClient->process()
#3 vendor/kevinoo/phpwhois/src/Handlers/IpHandler.php(144): phpWhois\Handlers\IpHandler->parse_results()
#4 vendor/kevinoo/phpwhois/src/WhoisClient.php(495): phpWhois\Handlers\IpHandler->parse()
#5 vendor/kevinoo/phpwhois/src/WhoisClient.php(271): phpWhois\WhoisClient->process()
#6 vendor/kevinoo/phpwhois/src/Whois.php(134): phpWhois\WhoisClient->getData()
#7 vendor/kevinoo/phpwhois/src/Whois.php(76): phpWhois\Whois->lookup()
#8 vendor/main/app-lib/src/Lib/Stateful/Whois.php(255): phpWhois\Whois->whois()
```

![image](https://github.com/kevinoo/phpWhois/assets/1065882/3720c00d-72fd-4873-ac8c-2080a8aa61a5)

**Comment by kevinoo** [comment]
Thanks @yespire !
Tomorrow I will fix it 💪🏻

**Comment by harikt** [comment]
This looks the fix https://github.com/kevinoo/phpWhois/compare/main...yespire:phpWhois:main . Could you please also verify and merge ?

**Comment by kevinoo** [comment]
Thanks @yespire ❤️
